/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Visibility the model 'Visibility'
type Visibility string

// List of Visibility
const (
	VISIBILITY_PRIVATE Visibility = "PRIVATE"
	VISIBILITY_SHARED Visibility = "SHARED"
	VISIBILITY_PUBLIC Visibility = "PUBLIC"
)
