/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GoogleSecurityKeys struct for GoogleSecurityKeys
type GoogleSecurityKeys struct {
	Data string `json:"data,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
