/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PlatformMetainfo struct for PlatformMetainfo
type PlatformMetainfo struct {
	Warnings []string `json:"warnings,omitempty"`
	JobQueues []AwsBatchPlatformMetainfoJobQueue `json:"jobQueues,omitempty"`
	Buckets []GooglePlatformMetainfoBucket `json:"buckets,omitempty"`
	FileSystems []AwsBatchPlatformMetainfoFsxFileSystem `json:"fileSystems,omitempty"`
	EfsFileSystems []AwsBatchPlatformMetainfoEfsFileSystem `json:"efsFileSystems,omitempty"`
	KeyPairs []string `json:"keyPairs,omitempty"`
	Vpcs []AwsBatchPlatformMetainfoVpc `json:"vpcs,omitempty"`
	Images []AwsBatchPlatformMetainfoImage `json:"images,omitempty"`
	SecurityGroups []AwsBatchPlatformMetainfoSecurityGroup `json:"securityGroups,omitempty"`
	Subnets []AwsBatchPlatformMetainfoSubnet `json:"subnets,omitempty"`
	InstanceFamilies []string `json:"instanceFamilies,omitempty"`
	AllocStrategy []string `json:"allocStrategy,omitempty"`
	Zones []string `json:"zones,omitempty"`
	Locations []string `json:"locations,omitempty"`
	Filestores []GooglePlatformMetainfoFilestore `json:"filestores,omitempty"`
}
