/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TraceCompleteRequest struct for TraceCompleteRequest
type TraceCompleteRequest struct {
	Workflow Workflow `json:"workflow,omitempty"`
	Metrics []WorkflowMetrics `json:"metrics,omitempty"`
	Progress TraceProgressData `json:"progress,omitempty"`
}
