/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListTeamResponse struct for ListTeamResponse
type ListTeamResponse struct {
	Teams []TeamDbDto `json:"teams,omitempty"`
}
