/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// NavbarConfigNavbarMenu struct for NavbarConfigNavbarMenu
type NavbarConfigNavbarMenu struct {
	Label string `json:"label,omitempty"`
	Url string `json:"url,omitempty"`
}
