/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EksComputeConfigAllOf struct for EksComputeConfigAllOf
type EksComputeConfigAllOf struct {
	// AWS region
	Region string `json:"region,omitempty"`
	// The AWS EKS cluster name
	ClusterName string `json:"clusterName,omitempty"`
	Environment []ConfigEnvVariable `json:"environment,omitempty"`
	WorkDir string `json:"workDir,omitempty"`
	PreRunScript string `json:"preRunScript,omitempty"`
	PostRunScript string `json:"postRunScript,omitempty"`
	Server string `json:"server,omitempty"`
	SslCert string `json:"sslCert,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	ComputeServiceAccount string `json:"computeServiceAccount,omitempty"`
	HeadServiceAccount string `json:"headServiceAccount,omitempty"`
	StorageClaimName string `json:"storageClaimName,omitempty"`
	StorageMountPath string `json:"storageMountPath,omitempty"`
	PodCleanup PodCleanupPolicy `json:"podCleanup,omitempty"`
	HeadPodSpec string `json:"headPodSpec,omitempty"`
	ServicePodSpec string `json:"servicePodSpec,omitempty"`
	HeadJobCpus int32 `json:"headJobCpus,omitempty"`
	HeadJobMemoryMb int32 `json:"headJobMemoryMb,omitempty"`
	// property to select the compute config platform
	Discriminator string `json:"discriminator,omitempty"`
}
