/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComputeRegion struct for ComputeRegion
type ComputeRegion struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
