/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SecurityKeys struct for SecurityKeys
type SecurityKeys struct {
	AccessKey string `json:"accessKey,omitempty"`
	SecretKey string `json:"secretKey,omitempty"`
	AssumeRoleArn string `json:"assumeRoleArn,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
	Data string `json:"data,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	Token string `json:"token,omitempty"`
	PrivateKey string `json:"privateKey,omitempty"`
	Passphrase string `json:"passphrase,omitempty"`
	Certificate string `json:"certificate,omitempty"`
	BatchName string `json:"batchName,omitempty"`
	BatchKey string `json:"batchKey,omitempty"`
	StorageName string `json:"storageName,omitempty"`
	StorageKey string `json:"storageKey,omitempty"`
	UserName string `json:"userName,omitempty"`
	Registry string `json:"registry,omitempty"`
	ConnectionId string `json:"connectionId,omitempty"`
	WorkDir string `json:"workDir,omitempty"`
}
