/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreatePipelineSecretResponse struct for CreatePipelineSecretResponse
type CreatePipelineSecretResponse struct {
	SecretId int64 `json:"secretId,omitempty"`
}
