/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreatePipelineSecretRequest struct for CreatePipelineSecretRequest
type CreatePipelineSecretRequest struct {
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
