/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrganizationDbDto struct for OrganizationDbDto
type OrganizationDbDto struct {
	OrgId int64 `json:"orgId,omitempty"`
	Name string `json:"name,omitempty"`
	FullName string `json:"fullName,omitempty"`
	Description string `json:"description,omitempty"`
	Location string `json:"location,omitempty"`
	Website string `json:"website,omitempty"`
	LogoId string `json:"logoId,omitempty"`
	LogoUrl string `json:"logoUrl,omitempty"`
	MemberId int64 `json:"memberId,omitempty"`
	MemberRole OrgRole `json:"memberRole,omitempty"`
}
