/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdatePipelineRequest struct for UpdatePipelineRequest
type UpdatePipelineRequest struct {
	Description string `json:"description,omitempty"`
	Icon string `json:"icon,omitempty"`
	Launch WorkflowLaunchRequest `json:"launch,omitempty"`
	LabelIds []int64 `json:"labelIds,omitempty"`
}
