/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateTeamMemberRequest struct for CreateTeamMemberRequest
type CreateTeamMemberRequest struct {
	UserNameOrEmail string `json:"userNameOrEmail,omitempty"`
}
