/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AzureSecurityKeys struct for AzureSecurityKeys
type AzureSecurityKeys struct {
	BatchName string `json:"batchName,omitempty"`
	BatchKey string `json:"batchKey,omitempty"`
	StorageName string `json:"storageName,omitempty"`
	StorageKey string `json:"storageKey,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
