/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// K8sSecurityKeys struct for K8sSecurityKeys
type K8sSecurityKeys struct {
	Certificate string `json:"certificate,omitempty"`
	PrivateKey string `json:"privateKey,omitempty"`
	Token string `json:"token,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
