/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GoogleLifeSciencesConfig struct for GoogleLifeSciencesConfig
type GoogleLifeSciencesConfig struct {
	Region string `json:"region,omitempty"`
	Zones []string `json:"zones,omitempty"`
	Location string `json:"location,omitempty"`
	WorkDir string `json:"workDir,omitempty"`
	Preemptible bool `json:"preemptible,omitempty"`
	BootDiskSizeGb int32 `json:"bootDiskSizeGb,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	SshDaemon bool `json:"sshDaemon,omitempty"`
	SshImage string `json:"sshImage,omitempty"`
	DebugMode int32 `json:"debugMode,omitempty"`
	CopyImage string `json:"copyImage,omitempty"`
	UsePrivateAddress bool `json:"usePrivateAddress,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	PreRunScript string `json:"preRunScript,omitempty"`
	PostRunScript string `json:"postRunScript,omitempty"`
	HeadJobCpus int32 `json:"headJobCpus,omitempty"`
	HeadJobMemoryMb int32 `json:"headJobMemoryMb,omitempty"`
	NfsTarget string `json:"nfsTarget,omitempty"`
	NfsMount string `json:"nfsMount,omitempty"`
	Environment []ConfigEnvVariable `json:"environment,omitempty"`
	// property to select the compute config platform
	Discriminator string `json:"discriminator,omitempty"`
}
