/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WorkflowQueryAttribute the model 'WorkflowQueryAttribute'
type WorkflowQueryAttribute string

// List of WorkflowQueryAttribute
const (
	WORKFLOWQUERYATTRIBUTE_OPTIMIZED WorkflowQueryAttribute = "optimized"
	WORKFLOWQUERYATTRIBUTE_LABELS WorkflowQueryAttribute = "labels"
)
