/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateWorkspaceResponse struct for CreateWorkspaceResponse
type CreateWorkspaceResponse struct {
	Workspace Workspace `json:"workspace,omitempty"`
}
