/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubmitWorkflowLaunchRequest struct for SubmitWorkflowLaunchRequest
type SubmitWorkflowLaunchRequest struct {
	Launch WorkflowLaunchRequest `json:"launch,omitempty"`
}
