/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ActionQueryAttribute the model 'ActionQueryAttribute'
type ActionQueryAttribute string

// List of ActionQueryAttribute
const (
	ACTIONQUERYATTRIBUTE_LABELS ActionQueryAttribute = "labels"
)
