/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CodeCommitSecurityKeys struct for CodeCommitSecurityKeys
type CodeCommitSecurityKeys struct {
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
