/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DescribeComputeEnvResponse struct for DescribeComputeEnvResponse
type DescribeComputeEnvResponse struct {
	ComputeEnv ComputeEnvResponseDto `json:"computeEnv,omitempty"`
}
