/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateComputeEnvRequest struct for CreateComputeEnvRequest
type CreateComputeEnvRequest struct {
	ComputeEnv ComputeEnv `json:"computeEnv,omitempty"`
	LabelIds []int64 `json:"labelIds,omitempty"`
}
