/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListRegionsResponse struct for ListRegionsResponse
type ListRegionsResponse struct {
	Regions []ComputeRegion `json:"regions,omitempty"`
}
