/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateCredentialsRequest struct for CreateCredentialsRequest
type CreateCredentialsRequest struct {
	Credentials CredentialsSpec `json:"credentials,omitempty"`
}
