/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DescribeTaskResponse struct for DescribeTaskResponse
type DescribeTaskResponse struct {
	Task Task `json:"task,omitempty"`
}
