/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WorkflowStatus the model 'WorkflowStatus'
type WorkflowStatus string

// List of WorkflowStatus
const (
	WORKFLOWSTATUS_SUBMITTED WorkflowStatus = "SUBMITTED"
	WORKFLOWSTATUS_RUNNING WorkflowStatus = "RUNNING"
	WORKFLOWSTATUS_SUCCEEDED WorkflowStatus = "SUCCEEDED"
	WORKFLOWSTATUS_FAILED WorkflowStatus = "FAILED"
	WORKFLOWSTATUS_CANCELLED WorkflowStatus = "CANCELLED"
	WORKFLOWSTATUS_UNKNOWN WorkflowStatus = "UNKNOWN"
)
