/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateAvatarResponse struct for CreateAvatarResponse
type CreateAvatarResponse struct {
	Avatar Avatar `json:"avatar,omitempty"`
	Url string `json:"url,omitempty"`
}
