/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListWorkspacesAndOrgResponse struct for ListWorkspacesAndOrgResponse
type ListWorkspacesAndOrgResponse struct {
	OrgsAndWorkspaces []OrgAndWorkspaceDbDto `json:"orgsAndWorkspaces,omitempty"`
}
