/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateComputeEnvResponse struct for CreateComputeEnvResponse
type CreateComputeEnvResponse struct {
	ComputeEnvId string `json:"computeEnvId,omitempty"`
}
