/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WspRole the model 'WspRole'
type WspRole string

// List of WspRole
const (
	WSPROLE_OWNER WspRole = "owner"
	WSPROLE_ADMIN WspRole = "admin"
	WSPROLE_MAINTAIN WspRole = "maintain"
	WSPROLE_LAUNCH WspRole = "launch"
	WSPROLE_VIEW WspRole = "view"
)
