/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PodCleanupPolicy the model 'PodCleanupPolicy'
type PodCleanupPolicy string

// List of PodCleanupPolicy
const (
	PODCLEANUPPOLICY_ON_SUCCESS PodCleanupPolicy = "on_success"
	PODCLEANUPPOLICY_ALWAYS PodCleanupPolicy = "always"
	PODCLEANUPPOLICY_NEVER PodCleanupPolicy = "never"
)
