/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListPipelinesResponse struct for ListPipelinesResponse
type ListPipelinesResponse struct {
	Pipelines []PipelineDbDto `json:"pipelines,omitempty"`
	TotalSize int64 `json:"totalSize,omitempty"`
}
