/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AgentSecurityKeys struct for AgentSecurityKeys
type AgentSecurityKeys struct {
	ConnectionId string `json:"connectionId,omitempty"`
	WorkDir string `json:"workDir,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
