/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TraceBeginResponse struct for TraceBeginResponse
type TraceBeginResponse struct {
	Status TraceProcessingStatus `json:"status,omitempty"`
	WorkflowId string `json:"workflowId,omitempty"`
	WatchUrl string `json:"watchUrl,omitempty"`
}
