/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateOrganizationRequest struct for CreateOrganizationRequest
type CreateOrganizationRequest struct {
	Organization Organization `json:"organization,omitempty"`
	LogoId string `json:"logoId,omitempty"`
}
