/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ActionSource the model 'ActionSource'
type ActionSource string

// List of Action.Source
const (
	ACTIONSOURCE_GITHUB ActionSource = "github"
	ACTIONSOURCE_TOWER ActionSource = "tower"
)
