/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Task struct for Task
type Task struct {
	Hash string `json:"hash,omitempty"`
	Name string `json:"name,omitempty"`
	Process string `json:"process,omitempty"`
	Tag string `json:"tag,omitempty"`
	Submit time.Time `json:"submit,omitempty"`
	Start time.Time `json:"start,omitempty"`
	Complete time.Time `json:"complete,omitempty"`
	Module []string `json:"module,omitempty"`
	Container string `json:"container,omitempty"`
	Attempt int32 `json:"attempt,omitempty"`
	Script string `json:"script,omitempty"`
	Scratch string `json:"scratch,omitempty"`
	Workdir string `json:"workdir,omitempty"`
	Queue string `json:"queue,omitempty"`
	Cpus int32 `json:"cpus,omitempty"`
	Memory int64 `json:"memory,omitempty"`
	Disk int64 `json:"disk,omitempty"`
	Time int64 `json:"time,omitempty"`
	Env string `json:"env,omitempty"`
	Executor string `json:"executor,omitempty"`
	MachineType string `json:"machineType,omitempty"`
	CloudZone string `json:"cloudZone,omitempty"`
	PriceModel CloudPriceModel `json:"priceModel,omitempty"`
	Cost float32 `json:"cost,omitempty"`
	ErrorAction string `json:"errorAction,omitempty"`
	ExitStatus int32 `json:"exitStatus,omitempty"`
	Duration int64 `json:"duration,omitempty"`
	Realtime int64 `json:"realtime,omitempty"`
	NativeId string `json:"nativeId,omitempty"`
	Pcpu float64 `json:"pcpu,omitempty"`
	Pmem float64 `json:"pmem,omitempty"`
	Rss int64 `json:"rss,omitempty"`
	Vmem int64 `json:"vmem,omitempty"`
	PeakRss int64 `json:"peakRss,omitempty"`
	PeakVmem int64 `json:"peakVmem,omitempty"`
	Rchar int64 `json:"rchar,omitempty"`
	Wchar int64 `json:"wchar,omitempty"`
	Syscr int64 `json:"syscr,omitempty"`
	Syscw int64 `json:"syscw,omitempty"`
	ReadBytes int64 `json:"readBytes,omitempty"`
	WriteBytes int64 `json:"writeBytes,omitempty"`
	VolCtxt int64 `json:"volCtxt,omitempty"`
	InvCtxt int64 `json:"invCtxt,omitempty"`
	Exit string `json:"exit,omitempty"`
	Id *int64 `json:"id,omitempty"`
	TaskId int64 `json:"taskId"`
	Status TaskStatus `json:"status"`
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
}
