/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ServiceInfo struct for ServiceInfo
type ServiceInfo struct {
	Version string `json:"version,omitempty"`
	ApiVersion string `json:"apiVersion,omitempty"`
	CommitId string `json:"commitId,omitempty"`
	AuthTypes []string `json:"authTypes,omitempty"`
	LoginPath string `json:"loginPath,omitempty"`
	Navbar NavbarConfig `json:"navbar,omitempty"`
	HeartbeatInterval int32 `json:"heartbeatInterval,omitempty"`
	UserWorkspaceEnabled bool `json:"userWorkspaceEnabled,omitempty"`
	AllowInstanceCredentials bool `json:"allowInstanceCredentials,omitempty"`
	LandingUrl string `json:"landingUrl,omitempty"`
	TermsOfUseUrl string `json:"termsOfUseUrl,omitempty"`
	ContentUrl string `json:"contentUrl,omitempty"`
	Analytics Analytics `json:"analytics,omitempty"`
	AllowLocalRepos bool `json:"allowLocalRepos,omitempty"`
	ContentMaxFileSize int64 `json:"contentMaxFileSize,omitempty"`
	WaveEnabled bool `json:"waveEnabled,omitempty"`
	WaveAllowedWorkspaces []int64 `json:"waveAllowedWorkspaces,omitempty"`
}
