/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Launch struct for Launch
type Launch struct {
	Id string `json:"id,omitempty"`
	ComputeEnv ComputeEnv `json:"computeEnv,omitempty"`
	Pipeline string `json:"pipeline"`
	WorkDir string `json:"workDir,omitempty"`
	Revision string `json:"revision,omitempty"`
	ConfigText string `json:"configText,omitempty"`
	TowerConfig string `json:"towerConfig,omitempty"`
	ParamsText string `json:"paramsText,omitempty"`
	PreRunScript string `json:"preRunScript,omitempty"`
	PostRunScript string `json:"postRunScript,omitempty"`
	MainScript string `json:"mainScript,omitempty"`
	EntryName string `json:"entryName,omitempty"`
	SchemaName string `json:"schemaName,omitempty"`
	Resume bool `json:"resume,omitempty"`
	ResumeLaunchId string `json:"resumeLaunchId,omitempty"`
	PullLatest bool `json:"pullLatest,omitempty"`
	StubRun bool `json:"stubRun,omitempty"`
	SessionId string `json:"sessionId,omitempty"`
	RunName string `json:"runName,omitempty"`
	ConfigProfiles []string `json:"configProfiles,omitempty"`
	UserSecrets []string `json:"userSecrets,omitempty"`
	WorkspaceSecrets []string `json:"workspaceSecrets,omitempty"`
	OptimizationId string `json:"optimizationId,omitempty"`
	HeadJobCpus int32 `json:"headJobCpus,omitempty"`
	HeadJobMemoryMb int32 `json:"headJobMemoryMb,omitempty"`
	DateCreated time.Time `json:"dateCreated"`
	LastUpdated time.Time `json:"lastUpdated,omitempty"`
}
