/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AwsBatchPlatformMetainfoFsxFileSystem struct for AwsBatchPlatformMetainfoFsxFileSystem
type AwsBatchPlatformMetainfoFsxFileSystem struct {
	Id string `json:"id,omitempty"`
	Dns string `json:"dns,omitempty"`
	Mount string `json:"mount,omitempty"`
}
