/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GithubActionConfig struct for GithubActionConfig
type GithubActionConfig struct {
	Events []string `json:"events,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
