/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PipelineQueryAttribute the model 'PipelineQueryAttribute'
type PipelineQueryAttribute string

// List of PipelineQueryAttribute
const (
	PIPELINEQUERYATTRIBUTE_OPTIMIZED PipelineQueryAttribute = "optimized"
	PIPELINEQUERYATTRIBUTE_LABELS PipelineQueryAttribute = "labels"
)
