/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TraceProgressResponse struct for TraceProgressResponse
type TraceProgressResponse struct {
	Status TraceProcessingStatus `json:"status,omitempty"`
	WorkflowId string `json:"workflowId,omitempty"`
}
