/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ListActionsResponseActionInfo struct for ListActionsResponseActionInfo
type ListActionsResponseActionInfo struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Pipeline string `json:"pipeline,omitempty"`
	Source ActionSource `json:"source,omitempty"`
	Status ActionStatus `json:"status,omitempty"`
	LastSeen time.Time `json:"lastSeen,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
	Event ActionEventType `json:"event,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	Labels []LabelDbDto `json:"labels,omitempty"`
	UsageCmd string `json:"usageCmd,omitempty"`
}
