/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ForgeConfig struct for ForgeConfig
type ForgeConfig struct {
	Type string `json:"type,omitempty"`
	MinCpus int32 `json:"minCpus,omitempty"`
	MaxCpus int32 `json:"maxCpus,omitempty"`
	GpuEnabled bool `json:"gpuEnabled,omitempty"`
	EbsAutoScale bool `json:"ebsAutoScale,omitempty"`
	InstanceTypes []string `json:"instanceTypes,omitempty"`
	AllocStrategy string `json:"allocStrategy,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	VpcId string `json:"vpcId,omitempty"`
	Subnets []string `json:"subnets,omitempty"`
	SecurityGroups []string `json:"securityGroups,omitempty"`
	FsxMount string `json:"fsxMount,omitempty"`
	FsxName string `json:"fsxName,omitempty"`
	FsxSize int32 `json:"fsxSize,omitempty"`
	DisposeOnDeletion bool `json:"disposeOnDeletion,omitempty"`
	Ec2KeyPair string `json:"ec2KeyPair,omitempty"`
	AllowBuckets []string `json:"allowBuckets,omitempty"`
	EbsBlockSize int32 `json:"ebsBlockSize,omitempty"`
	FusionEnabled bool `json:"fusionEnabled,omitempty"`
	BidPercentage int32 `json:"bidPercentage,omitempty"`
	EfsCreate bool `json:"efsCreate,omitempty"`
	EfsId string `json:"efsId,omitempty"`
	EfsMount string `json:"efsMount,omitempty"`
	DragenEnabled bool `json:"dragenEnabled,omitempty"`
	DragenAmiId string `json:"dragenAmiId,omitempty"`
	EbsBootSize int32 `json:"ebsBootSize,omitempty"`
}
