/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Avatar struct for Avatar
type Avatar struct {
	Id string `json:"id,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
	LastUpdated time.Time `json:"lastUpdated,omitempty"`
}
