/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ParticipantDbDto struct for ParticipantDbDto
type ParticipantDbDto struct {
	MemberId int64 `json:"memberId"`
	Email string `json:"email"`
	UserName string `json:"userName"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	ParticipantId int64 `json:"participantId"`
	OrgRole OrgRole `json:"orgRole"`
	TeamId int64 `json:"teamId"`
	TeamName string `json:"teamName"`
	WspRole WspRole `json:"wspRole"`
	TeamAvatarUrl string `json:"teamAvatarUrl,omitempty"`
	UserAvatarUrl string `json:"userAvatarUrl"`
	Type ParticipantType `json:"type,omitempty"`
}
