/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ParticipantType the model 'ParticipantType'
type ParticipantType string

// List of ParticipantType
const (
	PARTICIPANTTYPE_MEMBER ParticipantType = "MEMBER"
	PARTICIPANTTYPE_TEAM ParticipantType = "TEAM"
	PARTICIPANTTYPE_COLLABORATOR ParticipantType = "COLLABORATOR"
)
