/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComputeEnvStatus the model 'ComputeEnvStatus'
type ComputeEnvStatus string

// List of ComputeEnv.Status
const (
	COMPUTEENVSTATUS_CREATING ComputeEnvStatus = "CREATING"
	COMPUTEENVSTATUS_AVAILABLE ComputeEnvStatus = "AVAILABLE"
	COMPUTEENVSTATUS_ERRORED ComputeEnvStatus = "ERRORED"
	COMPUTEENVSTATUS_INVALID ComputeEnvStatus = "INVALID"
)
