/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TaskStatus the model 'TaskStatus'
type TaskStatus string

// List of TaskStatus
const (
	TASKSTATUS_NEW TaskStatus = "NEW"
	TASKSTATUS_SUBMITTED TaskStatus = "SUBMITTED"
	TASKSTATUS_RUNNING TaskStatus = "RUNNING"
	TASKSTATUS_CACHED TaskStatus = "CACHED"
	TASKSTATUS_COMPLETED TaskStatus = "COMPLETED"
	TASKSTATUS_FAILED TaskStatus = "FAILED"
	TASKSTATUS_ABORTED TaskStatus = "ABORTED"
)
