/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"os"
)
// InlineObject struct for InlineObject
type InlineObject struct {
	Image *os.File `json:"image,omitempty"`
}
