/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateLabelResponse struct for UpdateLabelResponse
type UpdateLabelResponse struct {
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
