/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AwsBatchConfig struct for AwsBatchConfig
type AwsBatchConfig struct {
	Region string `json:"region,omitempty"`
	ComputeQueue string `json:"computeQueue,omitempty"`
	DragenQueue string `json:"dragenQueue,omitempty"`
	ComputeJobRole string `json:"computeJobRole,omitempty"`
	ExecutionRole string `json:"executionRole,omitempty"`
	HeadQueue string `json:"headQueue,omitempty"`
	HeadJobRole string `json:"headJobRole,omitempty"`
	CliPath string `json:"cliPath,omitempty"`
	Volumes []string `json:"volumes,omitempty"`
	WorkDir string `json:"workDir,omitempty"`
	PreRunScript string `json:"preRunScript,omitempty"`
	PostRunScript string `json:"postRunScript,omitempty"`
	HeadJobCpus int32 `json:"headJobCpus,omitempty"`
	HeadJobMemoryMb int32 `json:"headJobMemoryMb,omitempty"`
	Environment []ConfigEnvVariable `json:"environment,omitempty"`
	WaveEnabled bool `json:"waveEnabled,omitempty"`
	Fusion2Enabled bool `json:"fusion2Enabled,omitempty"`
	NvnmeStorageEnabled bool `json:"nvnmeStorageEnabled,omitempty"`
	LogsGroup string `json:"logsGroup,omitempty"`
	Forge ForgeConfig `json:"forge,omitempty"`
	ForgedResources []map[string]map[string]interface{} `json:"forgedResources,omitempty"`
	// property to select the compute config platform
	Discriminator string `json:"discriminator,omitempty"`
}
