/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TeamDbDto struct for TeamDbDto
type TeamDbDto struct {
	TeamId int64 `json:"teamId,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	AvatarUrl string `json:"avatarUrl,omitempty"`
	MembersCount int64 `json:"membersCount,omitempty"`
}
