/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AwsBatchPlatformMetainfoJobQueue struct for AwsBatchPlatformMetainfoJobQueue
type AwsBatchPlatformMetainfoJobQueue struct {
	Name string `json:"name"`
	State string `json:"state"`
}
