/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateActionRequest struct for CreateActionRequest
type CreateActionRequest struct {
	Name string `json:"name,omitempty"`
	Source ActionSource `json:"source,omitempty"`
	Launch WorkflowLaunchRequest `json:"launch,omitempty"`
}
