/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AddMemberResponse struct for AddMemberResponse
type AddMemberResponse struct {
	Member MemberDbDto `json:"member,omitempty"`
}
