/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LaunchActionRequest struct for LaunchActionRequest
type LaunchActionRequest struct {
	Params map[string]map[string]interface{} `json:"params,omitempty"`
}
