/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RunLog struct for RunLog
type RunLog struct {
	RunId string `json:"run_id,omitempty"`
	Request RunRequest `json:"request,omitempty"`
	State State `json:"state,omitempty"`
	RunLog Log `json:"run_log,omitempty"`
	TaskLogs []Log `json:"task_logs,omitempty"`
	Outputs map[string]interface{} `json:"outputs,omitempty"`
}
