/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WorkflowMetrics struct for WorkflowMetrics
type WorkflowMetrics struct {
	Id *int64 `json:"id,omitempty"`
	Process string `json:"process"`
	Cpu ResourceData `json:"cpu,omitempty"`
	Mem ResourceData `json:"mem,omitempty"`
	Vmem ResourceData `json:"vmem,omitempty"`
	Time ResourceData `json:"time,omitempty"`
	Reads ResourceData `json:"reads,omitempty"`
	Writes ResourceData `json:"writes,omitempty"`
	CpuUsage ResourceData `json:"cpuUsage,omitempty"`
	MemUsage ResourceData `json:"memUsage,omitempty"`
	TimeUsage ResourceData `json:"timeUsage,omitempty"`
}
