/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WfManifest struct for WfManifest
type WfManifest struct {
	NextflowVersion string `json:"nextflowVersion,omitempty"`
	DefaultBranch string `json:"defaultBranch,omitempty"`
	Version string `json:"version,omitempty"`
	HomePage string `json:"homePage,omitempty"`
	Gitmodules string `json:"gitmodules,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
	MainScript string `json:"mainScript,omitempty"`
	Author string `json:"author,omitempty"`
}
