/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LabelType the model 'LabelType'
type LabelType string

// List of LabelType
const (
	LABELTYPE_SIMPLE LabelType = "simple"
	LABELTYPE_RESOURCE LabelType = "resource"
	LABELTYPE_ALL LabelType = "all"
)
