/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// User struct for User
type User struct {
	Id *int64 `json:"id,omitempty"`
	UserName string `json:"userName"`
	Email string `json:"email,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Organization string `json:"organization,omitempty"`
	Description string `json:"description,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	Notification bool `json:"notification,omitempty"`
	TermsOfUseConsent bool `json:"termsOfUseConsent,omitempty"`
	MarketingConsent bool `json:"marketingConsent,omitempty"`
	LastAccess time.Time `json:"lastAccess,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
	LastUpdated time.Time `json:"lastUpdated,omitempty"`
	Deleted bool `json:"deleted,omitempty"`
}
