/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AwsBatchPlatformMetainfoSubnet struct for AwsBatchPlatformMetainfoSubnet
type AwsBatchPlatformMetainfoSubnet struct {
	Id string `json:"id,omitempty"`
	Zone string `json:"zone,omitempty"`
	VpcId string `json:"vpcId,omitempty"`
}
