/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ContainerRegistryKeys struct for ContainerRegistryKeys
type ContainerRegistryKeys struct {
	UserName string `json:"userName,omitempty"`
	Password string `json:"password,omitempty"`
	Registry string `json:"registry,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
}
