/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// ComputeEnvResponseDto struct for ComputeEnvResponseDto
type ComputeEnvResponseDto struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Platform string `json:"platform,omitempty"`
	Config ComputeConfig `json:"config,omitempty"`
	DateCreated time.Time `json:"dateCreated,omitempty"`
	LastUpdated time.Time `json:"lastUpdated,omitempty"`
	LastUsed time.Time `json:"lastUsed,omitempty"`
	Deleted bool `json:"deleted,omitempty"`
	Status ComputeEnvStatus `json:"status,omitempty"`
	Message string `json:"message,omitempty"`
	Primary bool `json:"primary,omitempty"`
	CredentialsId string `json:"credentialsId,omitempty"`
	OrgId int64 `json:"orgId,omitempty"`
	WorkspaceId int64 `json:"workspaceId,omitempty"`
	Labels []LabelDbDto `json:"labels,omitempty"`
}
