/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// State the model 'State'
type State string

// List of State
const (
	STATE_UNKNOWN State = "UNKNOWN"
	STATE_QUEUED State = "QUEUED"
	STATE_INITIALIZING State = "INITIALIZING"
	STATE_RUNNING State = "RUNNING"
	STATE_PAUSED State = "PAUSED"
	STATE_COMPLETE State = "COMPLETE"
	STATE_EXECUTOR_ERROR State = "EXECUTOR_ERROR"
	STATE_SYSTEM_ERROR State = "SYSTEM_ERROR"
	STATE_CANCELED State = "CANCELED"
	STATE_CANCELING State = "CANCELING"
)
