/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RunStatus struct for RunStatus
type RunStatus struct {
	RunId string `json:"run_id,omitempty"`
	State State `json:"state,omitempty"`
}
