/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Log struct for Log
type Log struct {
	Name string `json:"name,omitempty"`
	Cmd []string `json:"cmd,omitempty"`
	StartTime string `json:"start_time,omitempty"`
	EndTime string `json:"end_time,omitempty"`
	Stdout string `json:"stdout,omitempty"`
	Stderr string `json:"stderr,omitempty"`
	ExitCode int32 `json:"exit_code,omitempty"`
}
