/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListWorkspacesResponse struct for ListWorkspacesResponse
type ListWorkspacesResponse struct {
	Workspaces []WorkspaceDbDto `json:"workspaces,omitempty"`
}
