/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TraceProcessingStatus the model 'TraceProcessingStatus'
type TraceProcessingStatus string

// List of TraceProcessingStatus
const (
	TRACEPROCESSINGSTATUS_OK TraceProcessingStatus = "OK"
	TRACEPROCESSINGSTATUS_KO TraceProcessingStatus = "KO"
)
