/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DescribePipelineSecretResponse struct for DescribePipelineSecretResponse
type DescribePipelineSecretResponse struct {
	PipelineSecret PipelineSecret `json:"pipelineSecret,omitempty"`
}
