/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TraceHeartbeatRequest struct for TraceHeartbeatRequest
type TraceHeartbeatRequest struct {
	Progress TraceProgressData `json:"progress,omitempty"`
}
