/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DescribeCredentialsResponse struct for DescribeCredentialsResponse
type DescribeCredentialsResponse struct {
	Credentials Credentials `json:"credentials,omitempty"`
}
