/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LogPageDownload struct for LogPageDownload
type LogPageDownload struct {
	FileName string `json:"fileName,omitempty"`
	DisplayText string `json:"displayText,omitempty"`
	SaveName string `json:"saveName,omitempty"`
}
