/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RunListResponse struct for RunListResponse
type RunListResponse struct {
	Runs []RunStatus `json:"runs,omitempty"`
	NextPageToken string `json:"next_page_token,omitempty"`
}
