/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListTasksResponse struct for ListTasksResponse
type ListTasksResponse struct {
	Tasks []DescribeTaskResponse `json:"tasks,omitempty"`
	Total int64 `json:"total,omitempty"`
}
