/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListPipelineInfoResponse struct for ListPipelineInfoResponse
type ListPipelineInfoResponse struct {
	Pipelines []string `json:"pipelines,omitempty"`
}
