/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AwsBatchPlatformMetainfoVpc struct for AwsBatchPlatformMetainfoVpc
type AwsBatchPlatformMetainfoVpc struct {
	Id string `json:"id,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
}
