/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CloudPriceModel the model 'CloudPriceModel'
type CloudPriceModel string

// List of CloudPriceModel
const (
	CLOUDPRICEMODEL_STANDARD CloudPriceModel = "standard"
	CLOUDPRICEMODEL_SPOT CloudPriceModel = "spot"
)
