/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DescribePlatformResponse struct for DescribePlatformResponse
type DescribePlatformResponse struct {
	Metainfo PlatformMetainfo `json:"metainfo,omitempty"`
}
