/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ComputeConfig struct for ComputeConfig
type ComputeConfig struct {
	// The GKE cluster region - or - zone
	Region string `json:"region,omitempty"`
	ComputeQueue string `json:"computeQueue,omitempty"`
	DragenQueue string `json:"dragenQueue,omitempty"`
	ComputeJobRole string `json:"computeJobRole,omitempty"`
	ExecutionRole string `json:"executionRole,omitempty"`
	HeadQueue string `json:"headQueue,omitempty"`
	HeadJobRole string `json:"headJobRole,omitempty"`
	CliPath string `json:"cliPath,omitempty"`
	Volumes []string `json:"volumes,omitempty"`
	WorkDir string `json:"workDir,omitempty"`
	PreRunScript string `json:"preRunScript,omitempty"`
	PostRunScript string `json:"postRunScript,omitempty"`
	HeadJobCpus int32 `json:"headJobCpus,omitempty"`
	HeadJobMemoryMb int32 `json:"headJobMemoryMb,omitempty"`
	Environment []ConfigEnvVariable `json:"environment,omitempty"`
	WaveEnabled bool `json:"waveEnabled,omitempty"`
	Fusion2Enabled bool `json:"fusion2Enabled,omitempty"`
	NvnmeStorageEnabled bool `json:"nvnmeStorageEnabled,omitempty"`
	LogsGroup string `json:"logsGroup,omitempty"`
	Forge AzBatchForgeConfig `json:"forge,omitempty"`
	ForgedResources []map[string]map[string]interface{} `json:"forgedResources,omitempty"`
	// property to select the compute config platform
	Discriminator string `json:"discriminator,omitempty"`
	Zones []string `json:"zones,omitempty"`
	Location string `json:"location,omitempty"`
	Preemptible bool `json:"preemptible,omitempty"`
	BootDiskSizeGb int32 `json:"bootDiskSizeGb,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
	SshDaemon bool `json:"sshDaemon,omitempty"`
	SshImage string `json:"sshImage,omitempty"`
	DebugMode int32 `json:"debugMode,omitempty"`
	CopyImage string `json:"copyImage,omitempty"`
	UsePrivateAddress bool `json:"usePrivateAddress,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	NfsTarget string `json:"nfsTarget,omitempty"`
	NfsMount string `json:"nfsMount,omitempty"`
	Spot bool `json:"spot,omitempty"`
	CpuPlatform string `json:"cpuPlatform,omitempty"`
	MachineType string `json:"machineType,omitempty"`
	HeadPool string `json:"headPool,omitempty"`
	AutoPoolMode bool `json:"autoPoolMode,omitempty"`
	TokenDuration string `json:"tokenDuration,omitempty"`
	DeleteJobsOnCompletion JobCleanupPolicy `json:"deleteJobsOnCompletion,omitempty"`
	DeletePoolsOnCompletion bool `json:"deletePoolsOnCompletion,omitempty"`
	LaunchDir string `json:"launchDir,omitempty"`
	UserName string `json:"userName,omitempty"`
	HostName string `json:"hostName,omitempty"`
	Port int32 `json:"port,omitempty"`
	MaxQueueSize int32 `json:"maxQueueSize,omitempty"`
	HeadJobOptions string `json:"headJobOptions,omitempty"`
	PropagateHeadJobOptions bool `json:"propagateHeadJobOptions,omitempty"`
	UnitForLimits string `json:"unitForLimits,omitempty"`
	PerJobMemLimit bool `json:"perJobMemLimit,omitempty"`
	PerTaskReserve bool `json:"perTaskReserve,omitempty"`
	Server string `json:"server,omitempty"`
	SslCert string `json:"sslCert,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	ComputeServiceAccount string `json:"computeServiceAccount,omitempty"`
	HeadServiceAccount string `json:"headServiceAccount,omitempty"`
	StorageClaimName string `json:"storageClaimName,omitempty"`
	StorageMountPath string `json:"storageMountPath,omitempty"`
	PodCleanup PodCleanupPolicy `json:"podCleanup,omitempty"`
	HeadPodSpec string `json:"headPodSpec,omitempty"`
	ServicePodSpec string `json:"servicePodSpec,omitempty"`
	// The GKE cluster name
	ClusterName string `json:"clusterName,omitempty"`
}
