/*
 * Nextflow Tower API
 *
 * Nextflow Tower service API
 *
 * API version: 1.0.0
 * Contact: info@seqera.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AddMemberRequest struct for AddMemberRequest
type AddMemberRequest struct {
	User string `json:"user,omitempty"`
}
